apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sofin
  template:
    metadata:
      labels:
        app: sofin
        name: web
        namespace: development
    spec:
      containers:
      - name: web
        image: sofinan/hw_sofin_dev:latest
        env:
        - name: connstr
          valueFrom: 
            secretKeyRef:
              name: secrets
              key: connstr
        ports:
          - containerPort: 5000
            name: http
            protocol: TCP
        resources:
          requests:
            cpu: 400m
        imagePullPolicy: Always
