apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
    app: demo
    namespace: production
spec:
  selector:
    name: web
  type: NodePort
  ports:
  - name: app-port
    port: 5000
    targetPort: 5000
    protocol: TCP

