apiVersion: v1
kind: Service
metadata:
  name: awsexp
  labels:
    name: awsexp
spec:
  selector:
    app: prometheus-cloudwatch-exporter
    release: prometheus-cloudwatch-exporter
  type: NodePort
  ports:
   - name: cloud-watch-port
     port: 9106
     targetPort: 9106
     protocol: TCP

