apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoexp
  template:
    metadata:
      labels:
        app: mongoexp
        name: web
    spec:
      containers:
      - name: mongoexp
        image: sofinan/mongoexp-ssl
        env:
        - name: ME_CONFIG_MONGODB_URL
          value: "mongodb://foo:mustbeeightchars@my-docdb-cluster.cluster-cvyuxvjadcvz.us-east-2.docdb.amazonaws.com:27017/?ssl=true&ssl_ca_certs=rds-combined-ca-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false" 
        ports:
          - containerPort: 8081
            name: http
            protocol: TCP
