apiVersion: v1
kind: Service
metadata:
  name: es
  labels:
    name: es
spec:
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: quickstart
    elasticsearch.k8s.elastic.co/statefulset-name: quickstart-es-default
  type: NodePort
  ports:
   - port: 9200
     targetPort: 9200
     protocol: TCP

