apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sofin
  template:
    metadata:
      labels:
        app: sofin
        name: web
    spec:
      containers:
      - name: web
        image: sofinan/hw_sofin:latest
        ports:
          - containerPort: 5000
            name: http
            protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        imagePullPolicy: Always
