apiVersion: v1
kind: Service
metadata:
  name: promui
  labels:
    name: promui
spec:
  selector:
    app= prometheus
    prometheus= prometheus-prometheus-oper-prometheus
  type: NodePort
  ports:
   - port: 9090
     targetPort: 9090
     protocol: TCP

