name: deploy_to_dev
      
# Controls when the action will run. 
on:
  # Triggers the workflow on push
  push:
    branches: [ development ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      MENV : development
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      #- name: build container
      #  run: docker build . --file Dockerfile --tag myapp:$(date +%s)
                 
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.1.0
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
      
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: sofinan/hw_sofin_dev
          tags: myapp, latest
          registry: docker.io
          buildArgs: BRANCH=env.MENV
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          
      - name: Deploy to Kubernetes cluster                                                              
        uses: kodermax/kubectl-aws-eks@master
        env:           
          RELEASE_IMAGE: sofinan/hw_sofin_dev:latest
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: rollout restart deployment/web -n env.MENV
      
      - name: Update deployment app
        uses: kodermax/kubectl-aws-eks@master
        env:
          RELEASE_IMAGE: sofinan/hw_sofin_dev:latest
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f k8s/app-depl-dev.yml -n env.MENV
    

      - name: Update hpa
        uses: kodermax/kubectl-aws-eks@master
        env:
          RELEASE_IMAGE: sofinan/hw_sofin_dev:latest
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f k8s/app-hpa-dev.yml -n env.MENV
      
      - name: Update load balancer
        uses: kodermax/kubectl-aws-eks@master
        env:
          RELEASE_IMAGE: sofinan/hw_sofin_dev:latest
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f k8s/app-srv-loadbalancer-dev.yml -n env.MENV
          
          
